name: building
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      with:
        image: my-new-image
        tags: branch-${{ github.ref_name }} ${{ github.sha }}
        containerfiles: diamond.containerfile
